version: '3.5'

services:

  app:
    hostname: 'app-${PROJECT_NAME}'
    container_name: 'app-${PROJECT_NAME}'
    build:
      dockerfile: Dockerfile.dev
      context: .
    networks:
      - local_dev_network
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      PORT: 4000
      DB_HOSTNAME: mongodb:27017
      DB_USERNAME: test
      DB_PASSWORD: test
      DB_DATABASE: apollo_gql_db

  mongodb:
    hostname: 'mongodb-${PROJECT_NAME}'
    container_name: 'mongodb-${PROJECT_NAME}'
    image: 'mongo:4.2.3'
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
    networks:
      - local_dev_network

networks:
  local_dev_network:
    driver: bridge
