version: "3"
vars:
  LOCAL_SERVICES: "app mongodb"
  COMPOSE_FILE: "COMPOSE_FILE=docker-compose.yml"
  BUILD_CMD: "docker-compose build --no-cache"
  RUN_CMD: "docker-compose up -d {{.LOCAL_SERVICES}}"
  RUN_APP_CMD: "docker-compose up -d app"
  BASH_CMD: "docker exec -it app-$PROJECT_NAME bash"
  INSTALL_DEPENDENCIES_CMD: "docker-compose run app yarn install --ignore-scripts"
  LOGS_CMD: "docker-compose logs -f --tail=500"
  LOGS_APP_CMD: "docker-compose logs -f --tail=500 app"
  STOP_CMD: "docker-compose down -v"
  TEST_CMD: "yarn test"

tasks:
  default:
    cmds:
      - task: run

  run:
    desc: Execute local project
    cmds:
      - task: build
      - '{{.RUN_CMD}}'

  build:
    desc: Build containers
    cmds:
      - '{{.BUILD_CMD}}'

  install:
    desc: Install dependencies
    cmds:
      - task: stop
      - task: build
      - '{{.INSTALL_DEPENDENCIES_CMD}}'

  stop:
    desc: Stop containers
    cmds:
      - '{{.STOP_CMD}}'

  restart:
    desc: Recreate containers
    cmds:
      - task: stop
      - task: run

  app:
    desc: Enter app bash
    cmds:
      - '{{.BASH_CMD}}'

  logs:
    desc: Docker logs
    cmds:
      - '{{.LOGS_CMD}}'

  logs:app:
    desc: Docker app logs
    cmds:
      - '{{.LOGS_APP_CMD}}'

  test:
    desc: Execute tests
    cmds:
      - '{{.TEST_CMD}}'
